### ISSUE TITLE
Visual bugs on Rewards page (date, etc)

### ISSUE THREAD

**Issue by NadiaIv** [AdExNetwork/adex-staking#123]
We've had reports of two things for the [Rewards page](https://staking.adex.network/#/rewards):

1. Date for Tom is wrong: currently says Tom (Incentive) 12.2020 - 3.2021
2. The total rewards don't change, see screenshot below

![](https://help.adex.network/attachments/token/Fd5u7lHYZj6yys3s8h7KP02zU/?name=d2d38090-5aec-40e0-8f66-058d33d075c2_image.png)

**Comment by Ivshti** [comment]
Turns out this just required a bit of thought and is a result of weird UX

The rewards from the old pool up until march are shown on the Rewards page

However, the rewards from the new pool are not showed at all at this page

This user just has uclaimed rewards from the old pool and that's what's causing the confusion

@NadiaIv
