### ISSUE TITLE
Identity nonce bug when issuing two or more consecutive transactions

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-staking#90]

**Comment by IvoPaunov** [comment]
Currently there is no good solution form the following:
 1 - Keeping identity nonce locally  and make new executes with updated nonce - this way we need to add the gas limit because otherwise the wallet provider will throw on gas estimation if the previous transaction(s) are not mined. This is the most usable solution at this moment but it can bring complications and more bugs.

2 - Getting pending transaction and displaying alert on transaction action. This is the best way but there is no easy way to get the pending transactions for the identity.  [Infura](https://infura.io/), [Alchemy](https://alchemyapi.io/), and few more providers returns same result of `transactionsCount` for `pending` and `latest`. [etherscan apis](https://etherscan.io/apis#stats) are returning higher `pending` count but only for the `wallet` and this is not what we need. We need to know if there are pending transactions to the identity as this https://etherscan.io/txsPending?a=0xe42A6FF5D92B002595c0900971231e300D2312f4&m=hf but I didn't find any way different than using own node and using web3 [getPendingTransactions](https://web3js.readthedocs.io/en/v1.3.0/web3-eth.html?highlight=getpendingTransactions#getpendingtransactions) or something similar to filter the transactions by `to === identityAddr`. Using provider `on pending` returns only tx hash and will not work.
